# 服务器配置
server:
  port: 1010
  ssl:  # 你漏了这个核心层级！所有 SSL 相关配置都要放在 ssl 节点下
    key-store: classpath:keystore.p12        # 证书在resources目录下
    key-store-password: 123456         # 必须和转换命令的密码一致
    key-store-type: PKCS12
    key-alias: tomcat

#spring
spring:
  #???mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cat_recommend_system?useUnicode=true&characterEncoding=utf8
    username: root
    password: "@1234Qwer.."
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # ???????????????? Swagger 2.9.2
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER # ?? Swagger ??? ANT ??????

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cat_card.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

